"""add Availability model

Revision ID: cc697fe94c62
Revises: 015a155a8b38
Create Date: 2026-01-23 07:01:01.360590

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "cc697fe94c62"
down_revision = "015a155a8b38"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Availability",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["Artist.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Availability")
    # ### end Alembic commands ###
