"""added constraints

Revision ID: f886b15ec138
Revises: b44a79a2177b
Create Date: 2026-01-26 06:21:59.396323

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "f886b15ec138"
down_revision = "b44a79a2177b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Artist", schema=None) as batch_op:
        batch_op.alter_column("name", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column(
            "city", existing_type=sa.VARCHAR(length=120), nullable=False
        )
        batch_op.alter_column(
            "state", existing_type=sa.VARCHAR(length=120), nullable=False
        )

    with op.batch_alter_table("Venue", schema=None) as batch_op:
        batch_op.alter_column("name", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column(
            "city", existing_type=sa.VARCHAR(length=120), nullable=False
        )
        batch_op.alter_column(
            "state", existing_type=sa.VARCHAR(length=120), nullable=False
        )
        batch_op.alter_column(
            "address", existing_type=sa.VARCHAR(length=120), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Venue", schema=None) as batch_op:
        batch_op.alter_column(
            "address", existing_type=sa.VARCHAR(length=120), nullable=True
        )
        batch_op.alter_column(
            "state", existing_type=sa.VARCHAR(length=120), nullable=True
        )
        batch_op.alter_column(
            "city", existing_type=sa.VARCHAR(length=120), nullable=True
        )
        batch_op.alter_column("name", existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table("Artist", schema=None) as batch_op:
        batch_op.alter_column(
            "state", existing_type=sa.VARCHAR(length=120), nullable=True
        )
        batch_op.alter_column(
            "city", existing_type=sa.VARCHAR(length=120), nullable=True
        )
        batch_op.alter_column("name", existing_type=sa.VARCHAR(), nullable=True)

    # ### end Alembic commands ###
